name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.5.0
        with:
          buildx-version: latest
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: build the image
        run: |
          docker buildx build \
            --push \
            --tag mickbird/sample-docker-rclone:${{steps.vars.outputs.tag}} mickbird/sample-docker-rclone:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            .
