name: build our image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.5.0
        with:
          buildx-version: latest
          
      - name: login to docker up
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: build the image
        run: |
          docker buildx build \
            --push \
            --tag mickbird/sample-docker-rclone:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            .
